### ISSUE TITLE
Hotspot name not changing immediately

### ISSUE THREAD

**Issue by prajurock** [opendatakit/skunkworks-crow#153]
#### Software and hardware versions 
Android v8.1.0, device used Asus max m1

#### Problem description
Hotspot name not changing immediately

#### Step to reproduce
1.open settings
2.click on Hotspot SSIS
3 Change name
4 Name is not changing

#### Expected behavior
name should be change immediately

![Uploading video2gif_20190302_144441.gif…](GIF)

**Comment by lakshyagupta21** [comment]
@prajurock Can you upload the gif again so that we can understand what the issue is?

**Comment by prajurock** [comment]
![GIF](https://user-images.githubusercontent.com/26791135/53683899-89b97980-3d2c-11e9-9d7f-d2d76db08c95.gif)

**Comment by prajurock** [comment]
@opendatakit-bot claim

**Comment by lakshyagupta21** [comment]
I think that feature is not supported yet, because for some devices its possible to change the hotspot name for some its not, that the reason its still in backlog, as much as I remember we can change the hotspot name on Android version < 8, for greater than 8 version it android system assigns some random SSID to hotspot which starts with AndroidShare, developer can't play with ssid names.
So you may have to disable the settings for some versions as well.

**Comment by lakshyagupta21** [comment]
@prajurock Are you still working on this?

**Comment by prajurock** [comment]
No i am not woking on this.

**Comment by Chromicle** [comment]
As @prajurock is not working on this issue I will work on this @lakshyagupta21

**Comment by Chromicle** [comment]
@opendatakit-bot claim
