### ISSUE TITLE
[Feature] Build the default transferring mechanism

### ISSUE THREAD

**Issue by huangyz0918** [opendatakit/skunkworks-crow#266]
#### Problem description
In #260 , we added a new approach using bluetooth. 
Currently, we will ask users to choose a transfer method every time when they are trying to sen/receive forms. Should we ask them every time? Can we set a default method and auto switch to another method if the default failed? 

According to my proposal, we can set the default method in our system settings, so we need to refactor the method choosing dialog, and we can build a better UI/UX based on this refactor.

What do you think about that? @lakshyagupta21 @shobhitagarwal1612 @Chromicle 
#### Expected behavior

We shall have a default method, and if the default method has any issue or crashed while transferring data, we can auto switch to the other one (bluetooth/hotspot).

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs discussion"

**Comment by huangyz0918** [comment]
Another task is to improve the UI in the bluetooth sender/receiver pages.
|||
|:--:|:--:|
|![Screenshot_19700107-002737](https://user-images.githubusercontent.com/15646062/60971226-40baa700-a356-11e9-8e58-7fc1b30e91e5.png)|![Screenshot_19700107-002716](https://user-images.githubusercontent.com/15646062/60971229-42846a80-a356-11e9-862f-8f75a70bb5d0.png)|

I don't like the UI, they are too simple, and although we are a functional application but I think if we have time I can build and design a better UI for that.

**Comment by lakshyagupta21** [comment]
@huangyz0918 As discussed over the call that we're going with adding an option to select the default mode in settings and during form transfer we've to notify/show some information about the mode through which transfer is happening(this is required so that receiver can set the same mode to receive the forms). And also it would be good to add the colored icon for better visuality of user so that he can distinguish between the mode of transfer through which the transfer is happening. 

At every new form transfer transaction it would be good if we don't ask the mode of transfer, lets go with the default and then after some timeout then we can ask the user to fallback, we would not be falling back automatically because this might create some confusion between sender and receiver.

**Comment by huangyz0918** [comment]
@lakshyagupta21 I think I can get start with some UI design now, I'll draw some prototype diagram and design and post them here recently (for reviewing and discussing). But I won't update the changes into #260 because it is too large now, adding new changes will make it hard to review. If you can merge #260 to `dev` (according to this [comment](https://github.com/opendatakit/skunkworks-crow/pull/260#issuecomment-511218214)) or `master` branch, I can get start implementing the UI work (during your testing #260 , I can design the UI).

**Comment by huangyz0918** [comment]
We have several tasks to do for this issue.

- [ ] add new options (maybe new designs) in the `Settings`.
- [ ] remove the dialogs for selecting one of a transferring method.
- [ ] connect the default method selected in preference to our specific job.
- [ ] detect the timeout and errors while using the default method, build new dialogs for switching to another method.
